title: Product Page
hide: true
fields:
  title:
    type: title
    display: Title
    localizable: false
  subtitle:
    type: text
    display: Subtitle
  content:
    type: markdown
    display: Content
    cheatsheet: false
  hero_image:
    type: assets
    display: hero image
    container: hero-images
    folder: /
    max_files: 1
